services:
  - type: web
    name: tfg-crm-backend
    env: docker
    plan: free
    dockerContext: backend/backend
    dockerfilePath: backend/backend/Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: tfg-crm-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tfg-crm-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: tfg-crm-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: tfg-crm-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tfg-crm-db
          property: password
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: PORT
        value: 10000
      - key: WHATSAPP_API_TOKEN
        value: EAARdZA7ntlx8BQ9gVvTR91lfpDZCrcReqsKIShaqDxYVqZATflPl9lASgM73VZCPnVBNQTzAvu7b4PAG3lpR7bwXBsjYvBAf9Uq0aYU33CqZBiIum3nMZACjghAEZCXFO1ZB2sWdoH82eetf7Fn4ZCqwBznvo6fZCFSyRaIzsmrOUSMrZBNuoDvhwVZCniXwZCGssCGYPRkqXO07Qsw3RCf7elQ0KStjxIQFZBATMiraLJPBTqhQE60Xxv5OpKSbr3rOlQZBzxa3to6BenoErqHCpn1UIZCGXUjC
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: 54641200506

databases:
  - name: tfg-crm-db
    plan: free
    databaseName: crmdb
    user: crmuser

version: "1"
