spring.datasource.url=jdbc:h2:file:./data/crmdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Meta Webhooks Configuration
meta.verify.token=TFG_CRM_2026
meta.app.secret=94a2210f20f262782a4bd53a6c8c35c5
